<?php
/**
 * @file
 * Membership Module file.
 */

/**
 * Implements hook_help().
 */
function membership_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#membership":
      $output = t("Administer all aspects of BMW Motorrad Club Cape Membership.");
      break;
  }
  return $output;
}

/**
 * Implements hook_perm().
 */
function membership_perm() {
  return array(
    'create membership',
    'edit own membership',
    'administer membership',
  );
}

/**
 * Implements hook_menu().
 */
function membership_menu() {
  $items = array();
  $items['membership/new'] = array(
    'title' => 'Join BMW Motorrad Club Cape',
    'description' => 'Create a new member record',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('membership_edit_form'),
    'access arguments' => array('create membership'),
    'file' => 'membership.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function membership_theme() {
  return array(
    'theme_membership_edit_form' => array(
      'template' => 'membership-edit-form',
      'arguments' => array('form' => NULL),
    ),
  );
}

// vim: set et ft=php sw=2 ai:
